create sequence fbtb_command_request_seq;

create table fbtb_command_request(
    request_id bigint
    , command_id bigint
    , created timestamp default current_timestamp
    , from_chat_id bigint
    , from_user_id bigint
    , command_arguments varchar(1024)
    , request_text blob sub_type text
    , result_statement blob sub_type text
    , result_text blob sub_type text
    , result_sent timestamp
    , result_response blob sub_type text
    , url varchar(1024)
    , http_method varchar(16)
    , status smallint
    , status_info varchar(1024)
    , status_updated timestamp
    , subscription_id bigint
    , constraint pk_fbtb_command_request primary key (request_id)
);

comment on table fbtb_command_request is 'Stores information about all received or generated by subscription command requests.';
comment on column fbtb_command_request.request_id is 'todo:';

comment on column fbtb_command_request.status is 'todo: 0 - unprocessed, 1 - result is waiting for send, 2 - sent, 3 - ignored/skipped, 4 - failed';
